stages:
  - build
  - deploy

docker_build:
  image: docker:24.0.7
  stage: build
  variables:
    APP_NAME: "sebsabi-frontend-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${$APP_NAME}${CI_PROJECT_NAME}:$CI_COMMIT_SHA
  before_script:
    # - apk add git
    - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE -f dockerfile .
    - docker push $DOCKER_IMAGE
  
update-manifest:
    stage: deploy
    variables:
        APP_NAME: "sebsabi-frontend-"
        DOCKER_IMAGE: $DOCKER_USER_NAME/${$APP_NAME}${CI_PROJECT_NAME}:$CI_COMMIT_SHA
        MANIFEST_GIT_REPO: https://$USERNAME:$PAT_TOKEN@git.gebeya.training/sebsabi-capstone/deployment-manifests.git
    before_script:
        - apk add git
        - git clone $MANIFEST_GIT_REPO
        - git config --global user.name "$GITLAB_USER_NAME"
        - git config --global user.email "$GITLAB_USER_EMAIL"
    script:
        - cd deployment-manifests
        - git remote set-url origin --push $MANIFEST_GIT_REPO
        - |
            sed -i "s#image:.*#image: ${DOCKER_IMAGE}#g" ./frontend/frontend-deployment.yaml
        - git stage ./frontend/frontend-deployment.yaml
        - git commit -m "Update the frontend image tag [skip-ci]"
        - git push origin main:$CI_COMMIT_REF_NAME

